# Add/remove 'critical' label if issue contains the words 'urgent' or 'critical'
analytics:
    - '(analytics)'

attributes:
    - '(attributes)'

category explorer:
    - '(category explorer)'

critical:
    - '(critical|urgent)'

contribution:
    - '(contribution)'

darkmode:
    - '(darkmode|Dark mode)'

database:
    - '(database)'

dev mode:
    - '(dev mode)'

deeplinking:
    - '(deeplinking)'

ecoscore:
    - '(ecoscore|eco-score)'

editing:
    - '(editing)'

enhancement:
    - '(enhancement)'

fastlane:
    - '(fastlane)'

folksonomy engine:
    - '(folksonomy engine)'

gamification:
    - '(gamification)'

history:
    - '(history)'

help wanted:
    - '(help wanted)'

mlkit:
    - '(mlkit)'

matomo:
    - '(matomo)'

nutriscore:
    - '(nutriscore|nutri-score)'

offline:
    - '(offline)'

open beauty facts:
    - '(open beauty facts)'

open pet food facts:
    - '(open pet food facts)'

open products facts:
    - '(open products facts)'

high priority:
    - '(high priority)'

ingredients:
    - '(ingredients)'

image upload:
    - '(image upload|photo upload)'

local cache:
    - '(local cache)'

lists:
    - '(lists)'

launch:
    - '(launch)'

layout:
    - '(layout)'

low priority:
    - '(low priority)'

mockups available:
    - '(mockups available)'

nutrition facts:
    - '(nutrition facts)'

onboarding:
    - '(onboarding)'

preferences:
    - '(preferences)'

performance:
    - '(performance)'

privacy:
    - '(privacy)'

permissions:
    - '(permissions)'

packaging input:
    - '(packaging input)'

product page:
    - '(product page)'

road to scores:
    - '(road to scores)'

robotoff:
    - '(robotoff)'

refactoring:
    - '(Refactoring)'

scan:
    - '(scan)'

sentry:
    - '(sentry)'

summary tab:
    - '(summary tab)'

splashscreen:
    - '(splashscreen)'

search:
    - '(search)'

screenshot generation:
    - '(screenshot-generation)'

svg:
    - '(svg)'

security:
    - '(security)'

speed:
    - '(speed)'

scanning:
    - '(scanning)'

settings:
    - '(settings)'

scan:
    - '(scan)'

translations:
    - '(translations)'

tests:
    - '(tests|test)'

ui/ux:
    - '(ui/ux|user interface|user experience)'
