language: android

jdk: oraclejdk8

env:
  global:
    - ANDROID_API_LEVEL=27
    - ANDROID_EMULATOR_LEVEL=21
    - ANDROID_BUILD_TOOLS_VERSION=28.0.3
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_TAG=google_apis
    - ADB_INSTALL_TIMEOUT=20 # minutes (2 minutes by default)
    - secure: "fpNJresszWHcOg8Qh4plu2RJFOv9AzCMh2dVV2SbwWNRuf2j15raDdFGhCD2tEM7ddhqrfHgmiwqFSWCzjWw1azx0ovGJfFhikLM741pLb68S/EkOdvl9RU6DXeC6+Tyg0iaustgkoK24kwkzx/kg3o56TyFg1g2ufsQqfEseJtOGVQEh86zj8ncfU60VcMP7HHqHZMjlZaQ+G0Ale4ofzQzmAbiNiNPjykMbjDhzdKMTeZLXnj8S59twI1y/D/JdfKCiq/xOnO3HbIZBZ4A3nVb/fV5WCR4Kw6LRzoNE9qYnxJFaeIYSF9+YDDol9PbQRWTX5EgDnJBbZqj8aSYUEk3WUGRnDCKYR0R/v/BhTfnLIp1jBQWyhDJ56iPZ+tgRfChMejsf8aH8agPwczjfbX8H/1NLzBAtF/elA67dPaoQMqb33nO8D+ESIIyYNsK4CyfeDF6/qT/IcBBa7FUfhIOHjwLnaeCyZS78eq2QUSNkDaATKM8BUot+hGMTenBpivEDKL1L+twFFFKjNK3HkvnJ2H92P/EgT7OUVSuPnD5czfK3WydMmbimChKoygSq5/62tC6FMHUNdNj7pHnfJWTdSj+RgNJKVTasPJAQ1B+pU/z+TZVJMsBpME2CTtNGC6+o9W/6K5FMUt/2J/P63RHJqXXZLtttphN3tg7eLo="
android:
  components:
    - tools
    - platform-tools
    - tools # to install Android SDK tools 25.1.x
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - android-$ANDROID_EMULATOR_LEVEL
    # For Google APIs
    - addon-google_apis-google-$ANDROID_API_LEVEL
    # Google Play Services
    - extra-google-google_play_services
    # Support library
    - extra-android-support
    # Latest artifacts in local repository
    - extra-google-m2repository
    - extra-android-m2repository
    # Specify at least one system image
    - sys-img-armeabi-v7a-google_apis-$ANDROID_EMULATOR_LEVEL

  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - '.*intel.+'

  before_cache:
    # Do not cache a few Gradle files/directories (see https://docs.travis-ci.com/user/languages/java/#Caching)
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    # Gradle dependencies
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

    # Cache maven
    - $HOME/.m2

before_script:
# Create and start emulator.
  - echo no | android create avd --force -n test -t "android-"$ANDROID_EMULATOR_LEVEL --abi $ANDROID_ABI --tag $ANDROID_TAG
  - emulator -avd test -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

before_install:
  - yes | sdkmanager "platforms;android-27"

jobs:
 include:
  - stage: test
    script:
      - ./gradlew testObfDebugUnitTest connectedObfDebugAndroidTest assembleObfDebug --stacktrace
      - mv app/build/outputs/apk/obf/debug/app-obf-debug.apk app/build/outputs/apk/app-obf-debug-$TRAVIS_BRANCH.apk

  - stage: test
    script:
      - ./gradlew testOffDebugUnitTest connectedOffDebugAndroidTest assembleOffDebug --stacktrace
      - mv app/build/outputs/apk/off/debug/app-off-debug.apk app/build/outputs/apk/app-off-debug-$TRAVIS_BRANCH.apk

  - stage: test
    script:
      - ./gradlew testOpfDebugUnitTest connectedOpfDebugAndroidTest assembleOpfDebug --stacktrace
      - mv app/build/outputs/apk/opf/debug/app-opf-debug.apk app/build/outputs/apk/app-opf-debug-$TRAVIS_BRANCH.apk

  - stage: test
    script:
      - ./gradlew testOpffDebugUnitTest connectedOpffDebugAndroidTest assembleOpffDebug --stacktrace
      - mv app/build/outputs/apk/opff/debug/app-opff-debug.apk app/build/outputs/apk/app-opff-debug-$TRAVIS_BRANCH.apk

sudo: required

notifications:
  email: false
  slack: openfoodfacts:mXLLSlWjBKA9e03ELQ83rNvB
  
before_deploy:
   # no GIT tag for debug apk
  - export TRAVIS_TAG=UNTAGGED
  
deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  draft: true
  file_glob: true
  api_key:
    secure: 1+rM47r/FmpfGHQRvO2DowV5qSlulmsQZseQ408Dra9HermLs8//HUTDEr+FZhJjnmUut6ykS1l7PalbQXdoNaHJSqe/BmD7crGYn/Cu/n0kRREzkCbl/YfH2oyRfP1wqMFWrMB+ItDgDU/MKnzi1JZRWTxNixoACPfGnTWTeu7iMeVkzIwr0LqBPSN8T1dOi8Kbd1KLXD59oUxb3eB+KIfZreP3Ro+mT8K89D44DVTyl6DuXzHaI/XivjAofq4hdsMs+X9YBVsH3iAnF8g0WvPfcfI881SQ20mQglJo7WL+97EtSqOgHk5dnTDKrkfrRU6OkFJ4yclkRSOaKoLKpCAJN9sJw8F4Mqip7PhF9hcUFI0LNjaZE28/anN55beNqs6AoZuaoesybGZWkxXTqKkWIryyWVsjy8MdjKRLKMBKQ1bIUafJ/K6itQL/doX2XbWToHT49zyIg8GT5nsjByM6i4nfHf5kcE8aCkZr16CH9/C44lEm7dSow+Pc+OOaYn81Ecgy9FEhk+plAgulgI+Xk9VqnheNdklcjJazbtjSaae+DbmOHkD1kLBsd7ENatE1nQVShwL7uMleSviamySgRaJTpmReR1UFMET5oYpRt9XHMJK47x1EsUtrwopgeghy1sUKNpQq/d5QpdFDyzI4MFBl/lZKe9r9TeyaGxg=
  file: app/build/outputs/apk/*.apk
  on:
    all_branches: true
