project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true
files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%android_code%/%original_file_name%
    languages_mapping:
      two_letters_code:
        pt-BR: pt-rBR
        pt-PT: pt-rPT
        zh-CN: zh-rCN
        en-AU: en-rAU
        en-GB: en-rGB
        nl-BE: nl-rBE
        nl: nl
        zh-TW: zh-rTW
        zh-HK: zh-rHK
        sr-CS: sr-rRS # Serbian, Latin
        me: sr-rME
        sr: sr # Serbian, Cyrillic
        he: iw
        id: in
        yi: ji

  - source: /app/src/obf/res/values/strings.xml
    dest: /app/src/obf/res/values/strings.xml
    translation: /app/src/obf/res/values-%two_letters_code%/%original_file_name%
    preserve_hierarchy: true
    languages_mapping:
      two_letters_code:
        zh-CN: zh-rCN
        en-GB: en-rGB
        pt-BR: pt-rBR
        en-AU: en-rAU
        pt-PT: pt-rPT
        nl-BE: nl-rBE
        nl: nl
        zh-HK: zh-rHK
        zh-TW: zh-rTW
        sr-CS: sr
        sr: rs
        he: iw
        id: in
        yi: ji

  - source: /app/src/off/res/values/strings.xml
    dest: /app/src/off/res/values/strings.xml
    translation: /app/src/off/res/values-%two_letters_code%/%original_file_name%
    preserve_hierarchy: true
    languages_mapping:
      two_letters_code:
        pt-BR: pt-rBR
        zh-CN: zh-rCN
        en-GB: en-rGB
        en-AU: en-rAU
        nl-BE: nl-rBE
        pt-PT: pt-rPT
        zh-HK: zh-rHK
        zh-TW: zh-rTW
        sr-CS: sr
        sr: rs
        he: iw
        id: in
        yi: ji

  - source: /app/src/opff/res/values/strings.xml
    dest: /app/src/opff/res/values/strings.xml
    translation: /app/src/opff/res/values-%two_letters_code%/strings.xml
    preserve_hierarchy: true
    languages_mapping:
      two_letters_code:
        zh-CN: zh-rCN
        en-GB: en-rGB
        en-AU: en-rAU
        pt-BR: pt-rBR
        nl-BE: nl-rBE
        pt-PT: pt-rPT
        zh-TW: zh-rTW
        zh-HK: zh-rHK
        sr-CS: sr
        sr: rs
        he: iw
        id: in
        yi: ji

  - source: /app/src/opf/res/values/strings.xml
    dest: /app/src/opf/res/values/strings.xml
    translation: /app/src/opf/res/values-%two_letters_code%/strings.xml
    preserve_hierarchy: true
    languages_mapping:
      two_letters_code:
        zh-CN: zh-rCN
        en-GB: en-rGB
        en-AU: en-rAU
        pt-BR: pt-rBR
        nl-BE: nl-rBE
        pt-PT: pt-rPT
        zh-TW: zh-rTW
        zh-HK: zh-rHK
        sr-CS: sr
        sr: rs
        he: iw
        id: in
        yi: ji

  - source: /fastlane/metadata/android/en-US/off/long_description.txt
    dest: /fastlane/metadata/android/en-US/off/long_description.txt
    translation: /fastlane/metadata/android/%locale%/off/long_description.txt
    preserve_hierarchy: true

  - source: /fastlane/metadata/android/en-US/obf/long_description.txt
    dest: /fastlane/metadata/android/en-US/obf/long_description.txt
    translation: /fastlane/metadata/android/%locale%/obf/long_description.txt
    preserve_hierarchy: true

  - source: /fastlane/metadata/android/en-US/opff/long_description.txt
    translation: /fastlane/metadata/android/%locale%/opff/long_description.txt
    dest: /fastlane/metadata/android/en-US/opff/long_description.txt
    preserve_hierarchy: true
    
  - source: /fastlane/metadata/android/en-US/opf/long_description.txt
    translation: /fastlane/metadata/android/%locale%/opf/long_description.txt
    dest: /fastlane/metadata/android/en-US/opf/long_description.txt
    preserve_hierarchy: true
    
  - source: /fastlane/metadata/android/en-US/off/short_description.txt
    translation: /fastlane/metadata/android/%locale%/off/short_description.txt
    dest: /fastlane/metadata/android/en-US/off/short_description.txt
    preserve_hierarchy: true
    
  - source: /fastlane/metadata/android/en-US/obf/short_description.txt
    translation: /fastlane/metadata/android/%locale%/obf/short_description.txt
    dest: /fastlane/metadata/android/en-US/obf/short_description.txt
    preserve_hierarchy: true
    
  - source: /fastlane/metadata/android/en-US/opff/short_description.txt
    translation: /fastlane/metadata/android/%locale%/opff/short_description.txt
    dest: /fastlane/metadata/android/en-US/opff/short_description.txt
    preserve_hierarchy: true
    
  - source: /fastlane/metadata/android/en-US/opf/short_description.txt
    translation: /fastlane/metadata/android/%locale%/opf/short_description.txt
    dest: /fastlane/metadata/android/en-US/opf/short_description.txt
    preserve_hierarchy: true
    
  - source: /fastlane/metadata/android/en-US/off/title.txt
    translation: /fastlane/metadata/android/%locale%/off/title.txt
    dest: /fastlane/metadata/android/en-US/off/title.txt
    preserve_hierarchy: true
    
  - source: /fastlane/metadata/android/en-US/off/changelogs/342.txt
    translation: /fastlane/metadata/android/%locale%/off/changelogs/342.txt
    dest: /fastlane/metadata/android/en-US/off/changelogs/342.txt
    preserve_hierarchy: true
    
  - source: /fastlane/metadata/android/en-US/obf/title.txt
    translation: /fastlane/metadata/android/%locale%/obf/title.txt
    dest: /fastlane/metadata/android/en-US/obf/title.txt
    preserve_hierarchy: true
    
  - source: /fastlane/metadata/android/en-US/opff/title.txt
    translation: /fastlane/metadata/android/%locale%/opff/title.txt
    dest: /fastlane/metadata/android/en-US/opff/title.txt
    preserve_hierarchy: true
    
  - source: /fastlane/metadata/android/en-US/opf/title.txt
    translation: /fastlane/metadata/android/%locale%/opf/title.txt
    dest: /fastlane/metadata/android/en-US/opf/title.txt
    preserve_hierarchy: true
    
  - source: /fastlane/metadata/android/en-US/off/screenshot-text.txt
    translation: /fastlane/metadata/android/%locale%/off/screenshot-text.txt
    dest: /fastlane/metadata/android/en-US/off/screenshot-text.txt
    preserve_hierarchy: true
    
  - source: /fastlane/metadata/android/en-US/off/feedback-form.txt
    translation: /fastlane/metadata/android/%locale%/off/feedback-form.txt
    dest: /fastlane/metadata/android/en-US/off/feedback-form.txt
    preserve_hierarchy: true
    
  - source: app/src/main/assets/changelog/changelog.json
    translation: app/src/main/assets/changelog/changelog-%locale%.json
    dest: app/src/main/assets/changelog/changelog.json
    preserve_hierarchy: true
    
