name: Feature Request (Guided)
description: Suggest an idea for this project
title: "[Feature]: "
labels: [feature, triage]
body:
  - type: dropdown
    id: flavor
    attributes:
      label: Flavor
      description: Does the feature concern Open Food Facts, Open Beauty Facts, Open Pet Food Facts or Open Products Facts?
      options:
        - Open Food Facts
        - Open Beauty Facts
        - Open Pet Food Facts
        - Open Products Facts
        - All of them
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.

