name: Android Feature Branch CI

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Compile screenshots
        run: bash ./gradlew compileOffScreenshotsAndroidTestSources --stacktrace --info -PtestBuildType=screenshots

      - name: Assemble OBF debug
        run: bash ./gradlew testObfDebugUnitTest assembleObfDebug --stacktrace

      - name: Assemble OFF debug
        run: bash ./gradlew testOffDebugUnitTest assembleOffDebug --stacktrace

      - name: Assemble OPF debug
        run: bash ./gradlew testOffDebugUnitTest assembleOpfDebug --stacktrace

      - name: Assemble OPFF debug
        run: bash ./gradlew testOffDebugUnitTest assembleOpffDebug --stacktrace