name: Android Integration

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  compile_screenshots:
    name: Compile Screenshot Tests
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2.4.0

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

      - name: Compile screenshots android tests
        uses: gradle/gradle-build-action@v2.1.2
        with:
          arguments: >
            compileOffPlaystoreScreenshotsAndroidTestSources 
            -PtestBuildType=screenshots


  test:
    name: Unit Tests
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2.4.0

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

      - name: Run unit tests
        uses: gradle/gradle-build-action@v2.1.2
        with:
          arguments: >
            testObfPlaystoreDebugUnitTest
            testOffPlaystoreDebugUnitTest
            testOpfPlaystoreDebugUnitTest
            testOpffPlaystoreDebugUnitTest


  assemble_apk:
    name: Assemble APKs
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2.4.0

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

      - name: Workaround for Android Gradle Plugin issue
        run: 'echo "ndk.dir=${ANDROID_HOME}/ndk-bundle" > local.properties'

      - name: Assemble debug APKs
        uses: gradle/gradle-build-action@v2.1.2
        with:
          arguments: assembleDebug

      - name: Upload OBF APKs
        uses: actions/upload-artifact@v2.3.1
        with:
          name: OBF
          path: |
            ./app/build/outputs/apk/obfPlaystore/debug/app-obf-playstore-debug.apk
            ./app/build/outputs/apk/obfFdroid/debug/app-obf-fdroid-debug.apk

      - name: Upload OFF APK
        uses: actions/upload-artifact@v2.3.1
        with:
          name: OFF
          path: |
            ./app/build/outputs/apk/offPlaystore/debug/app-off-playstore-debug.apk
            ./app/build/outputs/apk/offFdroid/debug/app-off-fdroid-debug.apk

      - name: Upload OPF APK
        uses: actions/upload-artifact@v2.3.1
        with:
          name: OPF
          path: |
            ./app/build/outputs/apk/opfPlaystore/debug/app-opf-playstore-debug.apk
            ./app/build/outputs/apk/opfFdroid/debug/app-opf-fdroid-debug.apk

      - name: Upload OPFF APK
        uses: actions/upload-artifact@v2.3.1
        with:
          name: OPFF
          path: |
            ./app/build/outputs/apk/opffPlaystore/debug/app-opf-playstore-debug.apk
            ./app/build/outputs/apk/opffFdroid/debug/app-opff-fdroid-debug.apk




  lint_off:
    name: Lint OFF
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2.4.0

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Workaround for Android Gradle Plugin issue
        run: "echo \"ndk.dir=${ANDROID_HOME}/ndk-bundle\" > local.properties"

      - name: Increase gradle daemon memory
        run: "echo \"org.gradle.jvmargs=-Xmx4096m\" >> gradle.properties"

      - name: Lint sources
        uses: gradle/gradle-build-action@v2.1.2
        with:
          arguments: lintOffPlayStoreDebug --stacktrace

      - name: Generate GitHub annotations
        uses: yutailang0119/action-android-lint@v2
        with:
          report-path: ./app/build/reports/lint-results-offPlaystoreDebug.xml

  build_deploy_pages:
    name: Deploy dokka to GitHub Pages
    runs-on: ubuntu-20.04

    needs:
      - assemble_apk
      - test

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2.4.0

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate documentation
        uses: gradle/gradle-build-action@v2.1.2
        with:
          arguments: dokkaHtml

      - name: Deploy documentation to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: app/build/dokka/html/
