name: Android Feature

on:
  push:
    branches:
      - '*'
      - '!develop'
      - '!master'
      - '!release/*'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Screenshots android tests
        run: bash ./gradlew compileOffPlaystoreScreenshotsAndroidTestSources --stacktrace --info -PtestBuildType=screenshots

      - name: Unit tests
        run: bash ./gradlew testObfPlaystoreDebugUnitTest testOffPlaystoreDebugUnitTest testOpfPlaystoreDebugUnitTest testOpffPlaystoreDebugUnitTest --stacktrace
