name: Android Pull Request & Master CI

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Screenshots android tests
        run: bash ./gradlew compileOffScreenshotsAndroidTestSources --stacktrace --info -PtestBuildType=screenshots

      - name: Unit tests
        run: bash ./gradlew testObfDebugUnitTest testOffDebugUnitTest testOpfDebugUnitTest testOpffDebugUnitTest --stacktrace

  apk:
    name: Generate APK
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build debug APKs
        run: bash ./gradlew assembleDebug --stacktrace

      - name: Upload OBF APK
        uses: actions/upload-artifact@v1
        with:
          name: obf
          path: app/build/outputs/apk/obf/debug/app-obf-debug.apk

      - name: Upload OFF APK
        uses: actions/upload-artifact@v1
        with:
          name: off
          path: app/build/outputs/apk/off/debug/app-off-debug.apk

      - name: Upload OPF APK
        uses: actions/upload-artifact@v1
        with:
          name: opf
          path: app/build/outputs/apk/opf/debug/app-opf-debug.apk

      - name: Upload OPFF APK
        uses: actions/upload-artifact@v1
        with:
          name: opff
          path: app/build/outputs/apk/opff/debug/app-opff-debug.apk