name: Android Integration

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  compile_screenshots:
    name: Compile Screenshot Tests
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Compile screenshots android tests
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: compileOffPlaystoreScreenshotsAndroidTestSources -PtestBuildType=screenshots

  test:
    name: Unit Tests
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Run unit tests
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: testObfPlaystoreDebugUnitTest testOffPlaystoreDebugUnitTest testOpfPlaystoreDebugUnitTest testOpffPlaystoreDebugUnitTest

  assemble_apk:
    name: Assemble APKs
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Workaround for Android Gradle Plugin issue
        run: "echo \"ndk.dir=${ANDROID_HOME}/ndk-bundle\" > local.properties"

      - name: Assemble debug APKs
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: assembleDebug --stacktrace

      - name: Upload OBF APK
        uses: actions/upload-artifact@v2.2.3
        with:
          name: obf
          path: app/build/outputs/apk/obf/debug/app-obf-debug.apk

      - name: Upload OFF APK
        uses: actions/upload-artifact@v2.2.3
        with:
          name: off
          path: app/build/outputs/apk/off/debug/app-off-debug.apk

      - name: Upload OPF APK
        uses: actions/upload-artifact@v2.2.3
        with:
          name: opf
          path: app/build/outputs/apk/opf/debug/app-opf-debug.apk

      - name: Upload OPFF APK
        uses: actions/upload-artifact@v2.2.3
        with:
          name: opff
          path: app/build/outputs/apk/opff/debug/app-opff-debug.apk

#  lint:
#    name: Lint
#    runs-on: ubuntu-20.04
#
#    steps:
#      - name: Checkout sources
#        uses: actions/checkout@v2
#
#      - name: Set up JDK 11
#        uses: actions/setup-java@v2
#        with:
#          distribution: 'adopt'
#          java-version: '11'
#
#      - name: Workaround for Android Gradle Plugin issue
#        run: "echo \"ndk.dir=${ANDROID_HOME}/ndk-bundle\" > local.properties"
#
#      - name: Increase gradle daemon memory
#        run: "echo \"org.gradle.jvmargs=-Xmx4096m\" > gradle.properties"
#
#      - name: Lint sources
#        uses: eskatos/gradle-command-action@v1
#        with:
#          arguments: lint --stacktrace
#
#      - name: Generate GitHub annotations
#        uses: yutailang0119/action-android-lint@v1.0.2
#        with:
#          xml_path: ./app/build/reports/lint-results.xml
