# This workflow performs a static analysis of your Kotlin source code using
# Detekt.
#
# Scans are triggered:
# 1. On every push to default and protected branches
# 2. On every Pull Request targeting the default branch
# 3. On a weekly schedule
# 4. Manually, on demand, via the "workflow_dispatch" event
#
# The workflow should work with no modifications, but you might like to use a
# later version of the Detekt CLI by modifing the $DETEKT_RELEASE_TAG
# environment variable.


name: Code static analysis

on:
  # Triggers the workflow on push or pull request events but only for default and protected branches
  push:
    branches: [ develop, master, release/* ]

  pull_request:
    branches: [ develop ]

  schedule:
    - cron: '0 5 * * 1'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  detekt:
    name: Detekt
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Run detekt
        uses: gradle/gradle-build-action@v2
        with:
          arguments: detekt

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v1
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: ${{ github.workspace }}/build/reports/detekt/detekt.sarif
          checkout_path: ${{ github.workspace }}

  semgrep:
    name: Semgrep
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          # more at semgrep.dev/explore
          config: >-
            p/security-audit
            p/secrets
          generateSarif: "1"

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: semgrep.sarif
        if: always()
