name: Crowdin Sync

on:
  push:
    branches: [ crowdin-trigger-per-language ]

jobs:
  synchronize-with-crowdin-matrix:
    name: Synchronize with crowdin (matrix)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
         lc: [it, fr, de, id, nl, da, es, pt, pt_PT, ar, ca, he]
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0
    - name: Matrix
      uses: crowdin/github-action@1.4.6
      with:
         upload_translations: false # default is false
         download_translations: true
         skip_untranslated_files: false
         commit_message: New Crowdin translations - ${{ matrix.lc }}
         localization_branch_name: l10n_develop_${{ matrix.lc }}
         pull_request_base_branch_name: develop
         pull_request_title: chore - New translations - ${{ matrix.lc }}
         pull_request_labels: "translations"
         download_language: ${{ matrix.lc }}
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
         CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
