    name: GitHub Pages Deploy Action
    on:
        push:
            branches:
                - "develop"
    jobs:
        deploy-pages:
            name: Deploy to GitHub Pages
            runs-on: ubuntu-latest
            steps:
            - uses: actions/checkout@v2
            - name: Set up JDK 12
              uses: actions/setup-java@v1
              with:
                java-version: 12
            - name: Grant execute permission for gradlew
              run: chmod +x gradlew
            #- name: Build and run tests
            #  run: ./gradlew build
            - name: Generate API documentation
              run: ./gradlew dokkaHtml
            - name: Deploy API documentation to Github Pages
              uses: JamesIves/github-pages-deploy-action@4.1.4
              with:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                BRANCH: gh-pages
                FOLDER: app/build/dokka/html/
                
