name: ktlint

on:
  pull_request:
    branches: 'ktlint'
jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
       - name: "checkout"
         uses: "actions/checkout@v4"
       - name: "ktlint"
         uses: "vroy/gha-kotlin-linter@v4"
